# Generated by Django 3.1.3 on 2021-02-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('img', models.CharField(default='', max_length=256)),
                ('time', models.CharField(default='', max_length=64)),
                ('content', models.CharField(default='', max_length=256)),
                ('classes_id', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=64)),
                ('content', models.CharField(default='', max_length=256)),
                ('img', models.CharField(default='', max_length=256)),
                ('author', models.CharField(default='', max_length=11)),
                ('classes', models.CharField(default='', max_length=11)),
                ('shenhe', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=256)),
                ('username', models.CharField(default='', max_length=64)),
                ('userinfo', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=128)),
                ('mobile', models.CharField(default='', max_length=128)),
                ('admin', models.BooleanField(default='False')),
            ],
        ),
    ]
